### ISSUE TITLE
Unhandled exception for Auth Failure

### ISSUE THREAD

**Issue by narasimhan-sridharan** [BirknerAlex/XMPPHP#2]
Hi guys!

Thanks for this module. Using this for building an internal chat platform here. 
However I noticed an issue when the AUTH fails. This is expected for my local system, so its not a configuration problem. 
https://code.google.com/p/xmpphp/issues/detail?id=53
This issue has been tracked here. I am not sure if XMPPHP officially has been updated yet, but this concurrency problem needs to be addressed, and since its a very minor fix, hoping the release would be done quickly. 
Thanks

**Comment by BirknerAlex** [comment]
Hello,

can you provide me please more information about the error what you got? If possible please also attach the full stacktrace of the exception. I've tested the library again and here it works fine. Please take also a look into my sample.

Note: The username needs to be provided without the @ and the domain name.

Sample:
```php
<?php
/**
 * Created by IntelliJ IDEA.
 * @author Alexander Birkner alex.birkner@gmail.com
 */
require_once __DIR__.'/../vendor/autoload.php';
$XMPP = new \BirknerAlex\XMPPHP\XMPP('jabber.domain.com', 5222, 'firstname.lastname', 'MySecretPassword', 'PHP');
$XMPP->connect();
$XMPP->processUntil('session_start', 10);
$XMPP->presence();
$XMPP->message('target.user@jabber.domain.com', 'Hello, how are you?', 'chat');
$XMPP->disconnect();
```

**Comment by BirknerAlex** [comment]
This issue has been closed due inactivity.
