### ISSUE TITLE
PHP7 support

### ISSUE THREAD

**Issue by KudrMichal** [BirknerAlex/XMPPHP#5]
Hi, 

I tried your project on php7 and it could be a problem in method calling by name in XMLStream.php.

For example...
$handler[1]->$handler[0]($this->xmlobj[2]);

call_user_func([$handler[1], $handler[0]], $this->xmlobj[2]);   is OK

I'm sorry for issue (I tried to send a PR, but I couldn't do git push origin through permissions)

Bye
Michal

**Comment by BirknerAlex** [comment]
Hey mkudr, 

to create a pull request you need to fork this repository. After forking you can checkout your repository (not mine). After you've pushed your changes to your repo you can create a pull request here and link your forked version. 

I hope that helps you to publish your fixes for PHP7. 

Regards,
Alexander

**Comment by BirknerAlex** [comment]
#7 has been merged now. This provides PHP 7 support.
